#!/usr/bin/env ruby
#
# Pre-requisites:
#
# git needs to be installed
# pkg-wizard build-bot needs to be running
#
# yum install rpmdevtools 
# gem install pkg-wizard
# gem install merb-core merb-slices merb-assets merb-helpers merb-haml moneta bunny uuidtools
# gem install rspec rake cucumber jeweler gemcutter
#
# See:
# http://wiki.opscode.com/display/chef/Installing+Chef+from+HEAD
#
require 'rubygems'
require 'pkg-wizard/rpm'
require 'fileutils'
require 'logger'
require 'rest-client'

Log = Logger.new('build-master.log')
$log = Log
BUILD_BOT_HOST = "localhost"
BASE_DIR = Dir.pwd
PKG_SRC_DIR = File.join(BASE_DIR, 'packages')
GEM_SRC_DIR = File.join(BASE_DIR, 'packages/sources')
CHEF_SRC_DIR = File.join(BASE_DIR, 'chef') 
CHEF_MODULES = %w{chef chef-server chef-server-api chef-server-webui chef-solr chef-expander}
SRC_RPMS_GIT_URLS = %w{
  git://github.com/frameos/rubygem-chef-server-rpm.git
  git://github.com/frameos/rubygem-chef-server-webui-rpm.git
  git://github.com/frameos/rubygem-chef-server-api-rpm.git
  git://github.com/frameos/rubygem-chef-rpm.git
  git://github.com/frameos/rubygem-chef-solr-rpm.git
  git://github.com/frameos/rubygem-chef-expander-rpm.git
}

MOCK_PROFILES = %w{
  rbel5-x86_64
  rbel5-i386
  rbel6-x86_64
  rbel6-i386
}

def debug(msg)
  puts "DEBUG: #{msg}" if not ARGV.include? '--quiet'
  $log.debug msg
end
def info(msg)
  puts "INFO: #{msg}"
  $log.info msg
end
def error(msg)
  puts "ERROR: #{msg}"
  $log.error msg
end

#
# Check if git command is available
#
if `which git`.strip.chomp.empty?
  error "git command not found."
  error "run 'yum install git' to install"
  exit 1
end

#
# Chef if rpmdevtools present
#
if `which rpmdev-setuptree`.strip.chomp.empty?
  error "rpmdevtools not found not found."
  error "run 'yum install rpmdevtools' to install"
  exit 1
end

info "----------------------------------------------------"
info " BUILDING CHEF MASTER #{Time.now.to_s}              "
info "----------------------------------------------------"

if not File.directory? File.join(CHEF_SRC_DIR, ".git")
  msg = "\nChef source directory not found."
  puts msg
  msg = "Do you want to fetch sources? (y/n): "
  print msg
  if $stdin.gets =~ /^(y|Y)/
    info "Fetching Chef sources from git://github.com/opscode/chef.git"
    debug `git clone git://github.com/opscode/chef.git 2>&1`
  else
    error "Chef source dir not found."
    exit 1
  end
end

FileUtils.mkdir_p GEM_SRC_DIR

#
# Clean previously generated gems
#

Dir.chdir CHEF_SRC_DIR

debug `git reset --hard`
debug `git pull`

#
# Build chef rubygems
#
packages = CHEF_MODULES
packages.each do |p|
  old_dir = Dir.pwd
  begin
    info "Building #{p} gem..."
    Dir.chdir p
    debug `rake package 2>&1`
    gem = Dir["pkg/*.gem"].first
    FileUtils.cp gem, GEM_SRC_DIR
  rescue Exception => e
    error "Error building #{p}: #{e.message}"
  ensure
    Dir.chdir old_dir
  end
end

Dir.chdir BASE_DIR 

#
# Create source RPMS
# 
packages.each do |p|
  src = File.join(PKG_SRC_DIR, "#{p}")
  if File.exist?("rubygem-#{p}-rpm/.git")
    # package sources already checked out, clean them
    info "Cleaning #{p} RPM sources"
    Dir.chdir src
    `git reset --hard`
    Dir.chdir BASE_DIR
  else
    Dir.chdir PKG_SRC_DIR
    url = SRC_RPMS_GIT_URLS.find { |u| u =~ /rubygem-#{p}-rpm/ }
    info "Fetching #{p} RPM sources"
    debug `git clone #{url} 2>&1`
    Dir.chdir BASE_DIR
  end
end

# 
# Copy gem to package source dir
#
Dir["#{GEM_SRC_DIR}/*.gem"].each do |g|
  gem_name = File.basename(g, '.gem').split('-')[0..-2].join('-')
  info "Updating #{gem_name} RPM sources"
  FileUtils.cp g, "#{PKG_SRC_DIR}/rubygem-#{gem_name}-rpm/"
end

# 
# Build SRPM
#
debug `rpmdev-setuptree 2>&1`
debug `rpmdev-wipetree 2>&1`
Dir["#{PKG_SRC_DIR}/*"].each do |d|
  next if d =~ /sources/ or not File.directory?(d)
  Dir.chdir d
  info "Creating #{d.split('/').last} SRPM"
  PKGWizard::SRPM.create
  Dir.chdir BASE_DIR
end

Dir.chdir BASE_DIR

info "SRPM packages available at #{ENV['HOME']}/rpmbuild/SRPMS"

#
# If --use-buildbot arg is used, use pkg-wizard's build-bot 
# to build the binary packages
#
if not ARGV.include?('--rhel5')
  MOCK_PROFILES.delete 'rbel5-i386'
  MOCK_PROFILES.delete 'rbel5-x86_64'
end
if not ARGV.include?('--rhel6')
  MOCK_PROFILES.delete 'rbel6-i386'
  MOCK_PROFILES.delete 'rbel6-x86_64'
end
if ARGV.include?('--use-buildbot')
  if MOCK_PROFILES.empty?
    info "Mock profiles not selected. Use either --rhel6 or --rhel5 arguments (or both)"
  else
    begin
      info "Cleaning build-bot old jobs"
      RestClient.post "http://#{BUILD_BOT_HOST}:4567/job/clean", {}
      MOCK_PROFILES.each do |profile|
        srpms_dir = "#{ENV['HOME']}/rpmbuild/SRPMS"
        Dir["#{srpms_dir}/*.rpm"].each do |pkg|
          info "Sending #{File.basename(pkg)} to build-bot (mock profile #{profile})"
          debug `pkgwiz remote-build -b #{BUILD_BOT_HOST} -m #{profile} #{pkg} 2>&1`
        end
      end
    rescue Exception => e
      error "Could not send clean command to build-bot"
    end
  end
end
